CREATE DATABASE IF NOT EXISTS ccet_db;
USE ccet_db;

CREATE TABLE IF NOT EXISTS Students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  course VARCHAR(100),
  year INT,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Teachers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  department VARCHAR(100),
  subject VARCHAR(100),
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role ENUM('admin', 'super-admin') DEFAULT 'admin',
  password VARCHAR(255) NOT NULL
);
